services:
  mongodb:
    image: mongo
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: BE-Architect
    ports:
      - "27017:27017"
networks:
  my-network:
    driver: bridge