services:
  mysql:
    image: mysql:8.0 
    container_name: be-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword 
      MYSQL_DATABASE: mysqldb 
      MYSQL_USER: huuloc2026 
      MYSQL_PASSWORD: 123456 
    ports:
      - "3306:3306" 
    networks:
      - my-network
  mongodb:
    image: mongo
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: BE-Architect
    ports:
      - "27017:27017"

    
networks:
  my-network:
    driver: bridge